version: '2'
services:
  neo4j:
    image: graanjonlo/neo4j:3.0.7
    ports:
     - "1337:1337"
     - "7473:7473"
     - "7474:7474"
     - "7687:7687"
    expose:
     - "1337"
     - "7473"
     - "7474"
     - "7687"
    volumes:
     - "/home/andy/docker/data/neo4j:/data"
     - "/home/andy/docker/logs/neo4j:/neo4j/logs"
    environment:
     - HEAP_INITIAL_SIZE=512
     - HEAP_MAX_SIZE=512
     - PAGECACHE_SIZE=1g
